server:
  port: 5555


spring:
  application:
    name: service-gateway

management:
    endpoints:
      web:
        exposure:
          include: "*"


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    baseservice: /base/**
    legacyservice:
      path: /legacy/**
      url: http://localhost:10000
    legacyservice2:
      path: /legacy2/**
      service-id: legacyservice2
  ignored-services:
  - baseservice

legacyservice2:
  ribbon:
    listOfServers:
      - localhost:10001
      - localhost:10002
      - localhost:10003



